config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/search',           to: 'static_pages#search'
  get    '/terms_of_service', to: 'users#terms_of_service'
  get    '/signup',           to: 'users#new'
  post   '/signup',           to: 'users#create'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  delete '/logout',           to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :password_resets, only:[:edit, :update]
  resources :posts,           only:[:new,:create, :show, :destroy] do
    resources :comments,      only: [:create, :destroy]
  end
  resources :relationships,   only: [:create, :destroy]
  resources :favorites,       only: [:create, :destroy]
  resources :notifications,   only: :index
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      @post.create_notification_comment(current_user, @comment.id)
      render :index
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment] ) do |form| %>
  <div>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit "コメントをする" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <p><%= link_to "#{comment.user.name}", user_path(comment.user.id) %></p>
    <p>コメント：<%= comment.content %></p>
    <% if comment.user == current_user %>
      <p><%= link_to 'コメントを削除する', post_comment_path(comment.post_id, comment.id), method: :delete, remote: true %></p>
    <% end %>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= escape_javascript(render 'index',  comments: @comment.post.comments) %>");
$("textarea").val('');