config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/search',           to: 'static_pages#search'
  get    '/terms_of_service', to: 'users#terms_of_service'
  get    '/signup',           to: 'users#new'
  post   '/signup',           to: 'users#create'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  delete '/logout',           to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers, :likes
    end
  end
  resources :password_resets, only:[:edit, :update]
  resources :posts,           only:[:new,:create, :show, :destroy] do
    resources :comments,      only: [:create, :destroy]
  end
  resources :relationships,   only: [:create, :destroy]
  resources :favorites,       only: [:create, :destroy]
  resources :notifications,   only: :index
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <%= link_to "写真を投稿する",new_post_path, class: "btn btn-lg btn-primary" %>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Insta Clone App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= form_tag(search_path, :method => 'get') do %>
            <%= text_field_tag :search%>
            <%= submit_tag "検索", :name => nil, class:"search_btn" %>
          <% end %>
        </li>
        <li><%= link_to "通知", notifications_url %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            アカウント <b class="caret"></b>
          </a>
         <ul class="dropdown-menu">
          <li><%= link_to "マイページ", current_user %></li>
            <% if  @user == current_user %>
          <li><%= link_to "編集", edit_user_path(current_user) %></li>
            <% end %>
          <li class="divider"></li>
          <li>
          <%= link_to "ログアウト", logout_path, method: :delete %>
          </li>
         </ul>
        </li>
        <% else %>
        <li><%= link_to "ログイン", login_path, class: "login-btn"%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_instaclone_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/instaclone_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer'%>
<%#  <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>